[package]
name = "actix_web_app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"     # Web framework for Rust
actix-rt = "2"      # Async runtime
serde = { version = "1", features = ["derive"] } # Serialization support

